### ISSUE TITLE
project roadmap

### ISSUE THREAD

**Issue by xfoxfu** [xfoxfu/ZhuiAni.me#1]
I think we should step to a roadmap till this weekend, i.e. Jul. 31. I pretty want to see this project working before anime fall season starts.

Here I have come up with some possible tasks (with order in which I think to be implemented):

- [x] prototype of user interface,
- [x] a working version of listing anime and torrents,
- [x] a scraper for animation metadata from [bangumi](https://bgm.tv),
- [x] a scraper for torrents from simple websites first, for example <https://bangumi.moe> and [dmhy](https://share.dmhy.org),
- [x] users, subscribing animations and RSS feed.

And here are some features I think to be postponed:

- [x] automatically download animation based on transmission.

cc @hez2010

**Comment by xfoxfu** [comment]
Here is a new database / object model design.

[![ZhuiAni.me Object Model](https://vip2.loli.io/2023/03/10/bnMOuTAUQtwJSzi.png)](https://excalidraw.com/#json=4o5HiTNuru2p7EeMXIc5j,GQCznj0JNSJijlXzzYWrfQ)

[![ZhuiAnime Object Model Example](https://vip2.loli.io/2023/03/10/9aPulDjdCRrb5nQ.png)](https://excalidraw.com/#json=5MKyZasy7n6JX2Ewm7T_d,0m5e9rD8-d5iFKvK5ddyHQ)

Detailed explanation will be added later. This design would extend ZhuiAni.me to a full-featured media library, which would make it more useful and extensible.

**Comment by xfoxfu** [comment]
[![image](https://github.com/xfoxfu/ZhuiAni.me/assets/3616727/1971b458-7f41-4d04-804d-e61def784295)](https://excalidraw.com/#json=MoE2LA__0BSdhn94mT2h7,YLP2EDJYO3vMW1zJ5t3xBw)

This is the proposal to an automated workflow of continuously discover new media into the library.


**Source**

Source provides list of new media items. However, these media items stays on the internet, and is not fetched locally.

```ts
{
  "name": "[*****duction&Lo*****se] ***** / W***d D*i S**r - 08 [W****p 1080p HEVC-10bit AAC][********]",
  "link": "magnet:?xt=urn:btih:4bd1b3197d9****************14ab68bb10826",
  "mime_type": "application/x-bittorrent"
}
```

Possible source could be:

- RSS
- MikanAni.me
- Pixiv

**Downloader**

Downloader could download items into another location based on information provided by _source_, such that the resource could be consumed. A downloader is not often required, in which case it is called _pass-through_. Downloader could be considered as a function from a link to another link.

Possible downloader could be:

- PikPak
- Transmission
- Aria2

**Scraper**

Scraper is an instance binding _source_ and _downloader_ together, and emits entities that ZhuiAni.me could consume. To provide more information to the user, it could possibly include a metadata query to websites like IMDB.

For example, a scraper instance would use RSS source to get animation videos, download them with PikPak, and finally queries BGM.tv for media info.

**Q&A**

- Where the filtering of source happens?
  
  It happens after the _source_ has got items, and is performed by ZhuiAni.me in a generic way. There could be a number of kinds of filters, such as _RegExp_, _When All_.

- What if the user wants to discover media on local machines?

  The _source_ would be disk scanning, and _downloader_ would be passing through. Then the scraper will find the metadata.

**TBD**

- It seems scraper takes too much role in discovering information. This seems quite similar to a traditional media server's scraper. Maybe there is a way to further split the role of scraper.
- Scraping information seems somehow coupled to the source.
- What if the user wants to import only animation information from BGM.tv to ZhuiAni.me?
- Scraper could be one-time or scheduled.
